FROM nginx:alpine

LABEL maintainer="CloudEats Development Team"
LABEL description="Nasi Lemak Paradise Menu - Static Website"
LABEL version="1.0"

COPY html/ /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/

EXPOSE 80
